### ISSUE TITLE
Pastelitos de membrillo

### ISSUE THREAD

**Issue by Agustoledo10** [pdepjm/2023-tp0-presentacion-RogerRamosAl#1]
Como andas Roger? Clavee los pastelitos de membrilloo y todo lo que tenga membrillo como las pepas jaja, igual los pastelitos los haces como los q son tipo hojaldre con muchas capas?? esos son mi debilidad jajaj

**Comment by RogerRamosAl** [comment]
Hola Agus como va, si mientras mas capas mejor también son mi debilidad jajaja
