### ISSUE TITLE
Calistenia

### ISSUE THREAD

**Issue by rvillani9** [pdepjm/2023-tp0-presentacion-RogerRamosAl#2]
Por que empezaste calistenia? Me gustaria empezar

**Comment by RogerRamosAl** [comment]
Hola Ramiro  como va? porque tengo un amigo que hace y dije fua re copado los trucos fue eso mas que nada. Y si te gusta empeza esta bueno igual te recomiendo obvio empezar chill ganar resistencia y fuerza después podes ir mejorando la técnica y ser constante supongo.
