### ISSUE TITLE
que tipazo

### ISSUE THREAD

**Issue by ikiknobel** [pdepjm/2023-tp0-presentacion-RogerRamosAl#4]
grande Rogerrr te rompiste el tp2 de AS. 
Foto de los avances considerables?? deaaa
Me fije recién y estamos en sintaxis también 👍

**Comment by RogerRamosAl** [comment]
> grande Rogerrr te rompiste el tp2 de AS. Foto de los avances considerables?? deaaa Me fije recién y estamos en sintaxis también 👍

Que onda iki  jajaj la foto al priv aca no deaa
